
import { UserAvatar } from '@/components/custom/UserAvatar'; 

export default function HomePage() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-24 bg-gradient-to-br from-background to-secondary">
      <div className="text-center mb-12">
        <h1 className="text-5xl font-bold mb-4 bg-gradient-to-r from-primary to-accent bg-clip-text text-transparent">
          Welcome to UserAvatar!
        </h1>
        <p className="text-xl text-muted-foreground">This component sandbox was generated by NexusAI using a template.</p>
      </div>
      
      <div className="w-full max-w-2xl p-8 bg-card rounded-xl shadow-2xl">
        <p className="text-center text-lg text-foreground mb-6">
          The following component, <strong>UserAvatar</strong>, was generated by AI:
        </p>
        <div className="border border-dashed border-border rounded-lg p-6 bg-background/50">
          <UserAvatar />
        </div>
      </div>

      <footer className="mt-16 text-center text-muted-foreground text-sm">
        <p>&copy; 2026 UserAvatar. Powered by NexusAI.</p>
      </footer>
    </main>
  );
}
